### ISSUE TITLE
Missing Celery Install

### ISSUE THREAD

**Issue by dvf** [paqman85/simple-celery-flower-on-heroku#2]
Firstly, thanks for doing this. I think it's a cool thing to have.

I did a fresh install on a new app, but noticed the following error:

```
2021-04-15T19:24:14.440303+00:00 heroku[web.1]: Starting process with command `flower --port=6172`
2021-04-15T19:24:17.572890+00:00 app[web.1]: Traceback (most recent call last):
2021-04-15T19:24:17.572915+00:00 app[web.1]: File "/app/.heroku/python/bin/flower", line 5, in <module>
2021-04-15T19:24:17.573152+00:00 app[web.1]: from flower.__main__ import main
2021-04-15T19:24:17.573182+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flower/__main__.py", line 4, in <module>
2021-04-15T19:24:17.573496+00:00 app[web.1]: from flower.command import FlowerCommand
2021-04-15T19:24:17.573525+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flower/command.py", line 17, in <module>
2021-04-15T19:24:17.573872+00:00 app[web.1]: from celery.bin.base import Command
2021-04-15T19:24:17.574033+00:00 app[web.1]: ImportError: cannot import name 'Command' from 'celery.bin.base' (/app/.heroku/python/lib/python3.9/site-packages/celery/bin/base.py)
2021-04-15T19:24:17.662565+00:00 heroku[web.1]: Process exited with status 1
2021-04-15T19:24:17.789032+00:00 heroku[web.1]: State changed from starting to crashed
```

I'm pretty sure that `celery` needs to be in `requirements.txt`?

**Comment by paqman85** [comment]
You're totally right!

Thanks for letting me know. 😄
